### ISSUE TITLE
Incorrect arch information inside debian11-armv8a packages

### ISSUE THREAD

**Issue by fmoule** [millicast/millicast-native-sdk#23] opened 2024-04-21 00:43 UTC
For a project using an AMD architecture on a debian distribution, millicast-native-sdk is needed there is no deb file for it.
So could you tell me if i can get one.

Thanks in advance.

**Comment by fmoule** [comment] 2024-04-21 01:01
My fault. 
To be more precise, i'm using an ARM architecture with debian 12:

This is the result of "lscpu" :

**Architecture:            aarch64
  CPU op-mode(s):        32-bit, 64-bit
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               ARM
  Model name:            Cortex-A72
    Model:               3
    Thread(s) per core:  1
    Core(s) per cluster: 4
    Socket(s):           -
    Cluster(s):          1
    Stepping:            r0p3
    CPU(s) scaling MHz:  33%
    CPU max MHz:         1800.0000
    CPU min MHz:         600.0000
    BogoMIPS:            108.00
    Flags:               fp asimd evtstrm crc32 cpuid
....
**

But when i try to install the **millicast-native-sdk-1.8.3-debian11-armv8a-nox11-nopulse-gnu-std.deb** package, i get the following error :

**dpkg: error processing archive millicast-native-sdk-1.8.3-debian11-armv8a-nox11-nopulse-gnu-std.deb (--install):
 package architecture (amd64) does not match system (arm64)**

Can you help me on this topic ?

Thanks in advance

**Comment by djova-dolby** [comment] 2024-04-23 08:17
As you can see this SDK is only for `armv8a`, so this SDK is meant for embedded linux boards. We support SDKs for Ubuntu20/Ubuntu22 for x64 machines.  There is no current plans to release `debian11-x64`. So best bet for linux x64 will be to use one of the Ubuntu ones.

**Comment by djova-dolby** [comment] 2024-04-24 14:30
My apologies I did not see the edited comment properly. I will take a look at this.

**Comment by djova-dolby** [comment] 2024-04-24 14:37
Oh yes I can reproduce:
```
dejan@dejan-desktop:~$ sudo dpkg -i millicast-native-sdk-1.8.3-debian11-armv8a-nox11-nopulse-gnu-std.deb 
[sudo] password for dejan: 
dpkg: error processing archive millicast-native-sdk-1.8.3-debian11-armv8a-nox11-nopulse-gnu-std.deb (--install):
 package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
 millicast-native-sdk-1.8.3-debian11-armv8a-nox11-nopulse-gnu-std.deb
```
I will have a look and let you know once it is fixed.

**Comment by djova-dolby** [comment] 2024-04-24 14:52
@fmoule ok so I have found the issue, this seems to be a bug with this packaging script introduced at some point that went undetected because during testing I would unpack like `dpkg-deb -x millicast-native-sdk-xxxxxx temp_dir` :D
As can be seen the binary is properly cross compiled and proper architecture, just information in the package is no bueno:
```
dejan@dejan-desktop:~/temp$ file usr/lib/libMillicastSDK.so.1.8.3 
usr/lib/libMillicastSDK.so.1.8.3: ELF 64-bit LSB shared object, ARM aarch64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=xxx, stripped
```
So until a release is ready with this fix please either unpack like:
```
dpkg-deb -x millicast-native-sdk-1.8.3-debian11-armv8a-nox11-nopulse-gnu-std.deb some_dir
```
and then work in some dir, or if you must have system wide installation override the bad info in the package:
```
sudo dpkg -i --force-architecture millicast-native-sdk-1.8.3-debian11-armv8a-nox11-nopulse-gnu-std.deb
```

**Comment by djova-dolby** [comment] 2024-04-24 18:39
Ok I have found the issue. It will be fixed in the 1.8.4 release coming soon.

**Comment by djova-dolby** [comment] 2024-04-25 12:48
@fmoule proper meta-data is located in the debian package now:
```
$ dpkg-deb --info millicast-native-sdk-1.8.4-debian11-armv8a-nox11-nopulse-gnu-std.deb 
 new Debian package, version 2.0.
...
 Architecture: arm64
 Description: Package for millicast-native-sdk
 Homepage: https://millicast.com
 Maintainer: Millicast
 Package: millicast-native-sdk
...
```
To summarize the package had correct architecture, but a bug in the packaging placed incorrect metadata in the debian package. The [workarounds explained here](https://github.com/millicast/millicast-native-sdk/issues/23#issuecomment-2075140757) made it possible to use the previous packages.
[Release 1.8.4](https://github.com/millicast/millicast-native-sdk/releases/tag/v1.8.4) has fixed this issue, as well as some other ones I found whilst fixing this one.

**Closed by djova-dolby** 2024-04-25 12:48 UTC

**Comment by djova-dolby** [comment] 2024-04-26 09:18
@fmoule when you get a chance can you confirm this is working for you? Apologies for the delay in the fix and initial missing of your edited comment. And thanks for using the linux arm64 sdk and reporting this issue!
