### ISSUE TITLE
Crash with `MCVideoTrack.removeRenderer()`

### ISSUE THREAD

**Issue by DanielKrofchick** [millicast/millicast-native-sdk#26] opened 2024-05-21 18:51 UTC
Not sure where best to post this, also posted it [here](https://github.com/millicast/millicast-sdk-swift-package/issues/1#issue-2308777163). Feel free to close the surplus one.

We are seeing a repeatable crash in the wild when calling `MCVideoTrack.removeRenderer()`, but so far have been unable to reproduce locally, and it may occur under very specific conditions,

> Fatal Exception: NSGenericException
*** Collection <__NSArrayM: 0x303da0ed0> was mutated while being enumerated.

My guess is there is a codepath in the framework that is not thread safe, and as the crash states, the `MCIosVideoRenderer` is removed immediately on call, while some other enumeration is in flight.

Do you have any insight into this crash, or anything we could be doing on our end to protect against this?

**Comment by Yousif-CS** [comment] 2024-05-22 04:48
Hey Daniel, which version of the SDK are you using?

**Comment by djova-dolby** [comment] 2024-05-22 11:11
Hi @DanielKrofchick,
Yes you were absolutley correct, from quick glance I was able to see multiple race-conditions in the ObjC SDK accessing objects in unsafe manner. @mxszym-dolby was able to reproduce the race calling remove/add from different threads, we have been testing the fix and it is working. So we will be including this in the upcoming 1.8.5 release, which should be out today. Will update here when it is released.
Thanks for reporting!

**Comment by djova-dolby** [comment] 2024-05-22 16:29
Fixed in [1.8.5](https://github.com/millicast/millicast-native-sdk/releases/tag/v1.8.5). The framework is available on github and through [SPM](https://github.com/millicast/millicast-sdk-swift-package/commit/8e8feebf07a75e60f4016498de00f60c586fa247). Due to some CI machine issues it is not yet published to CocoaPods.

**Closed by djova-dolby** 2024-05-22 16:29 UTC

**Comment by DanielKrofchick** [comment] 2024-05-22 17:23
Amazing! Thank you for the super quick turn around @djova-dolby.
